version: 2

updates:
  - allow:
      - dependency-type: direct
    commit-message:
      include: scope
      prefix: chore
    directory: /
    open-pull-requests-limit: 99
    package-ecosystem: github-actions
    schedule:
      interval: weekly
