export enum FileEncodings {
  'ascii' = 'ascii',
  'base64' = 'base64',
  'binary' = 'binary',
  'hex' = 'hex',
  'latin1' = 'latin1',
  'utf8' = 'utf8',
  'utf-8' = 'utf-8',
  'ucs2' = 'ucs2',
  'ucs-2' = 'ucs-2',
  'utf16le' = 'utf16le',
  'utf-16le' = 'utf-16le',
}

export enum FileExtension {
  json = 'json',
  js = 'js',
  coffee = 'coffee',
  html = 'html',
  txt = 'txt',
  csv = 'csv',
  png = 'png',
  jpg = 'jpg',
  jpeg = 'jpeg',
  gif = 'gif',
  tif = 'tif',
  tiff = 'tiff',
  zip = 'zip',
  pdf = 'pdf',
  vcf = 'vcf',
  svg = 'svg',
  xls = 'xls',
  xlsx = 'xlsx',
  doc = 'doc',
  docx = 'docx',
  mp3 = 'mp3',
  mp4 = 'mp4',
}
