name: feature

on:
  push:
    branches-ignore: [$default-branch]
  pull_request:
    branches: [$default-branch]

jobs:
  build:
    name: Build artifacts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  test-e2e:
    name: E2E tests
    needs: [build]
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.15.0-chrome86-ff82

    env:
      app_host: 'http://localhost:3000'
    strategy:
      matrix:
        cwd: [angularjs-ng-file-upload, react-dropzone, react-html5-input, shadow-dom-native]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: dist
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/Cypress
            node_modules
          key: test-e2e-${{ runner.os }}-${{ matrix.cwd }}
      - name: Install dependencies and verify Cypress
        uses: cypress-io/github-action@v2
        with:
          working-directory: ${{matrix.cwd}}
          runTests: false
      - name: Run web application
        run: npm start & # & helps to run daemonized app
        working-directory: ./recipes/${{matrix.cwd}}
      - name: Run Chrome tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./recipes/${{matrix.cwd}}
          install: false
          browser: chrome
          headless: false
          wait-on: ${{env.app_host}}
      - name: Run Chrome headless tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./recipes/${{matrix.cwd}}
          install: false
          browser: chrome
          headless: true
          wait-on: ${{env.app_host}}
      # - name: Run Firefox tests
      #   uses: cypress-io/github-action@v2
      #   with:
      #     working-directory: ./recipes/${{matrix.cwd}}
      #     install: false
      #     browser: firefox
      #     headless: false
      #     wait-on: ${{env.app_host}}
      # - name: Run Firefox headless tests
      #   uses: cypress-io/github-action@v2
      #   with:
      #     working-directory: ./recipes/${{matrix.cwd}}
      #     install: false
      #     browser: firefox
      #     headless: true
      #     wait-on: ${{env.app_host}}
      - name: Run Electron tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./recipes/${{matrix.cwd}}
          install: false
          browser: electron
          headless: false
          wait-on: ${{env.app_host}}
      - name: Run Electron headless tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./recipes/${{matrix.cwd}}
          install: false
          browser: electron
          headless: true
          wait-on: ${{env.app_host}}
